name: DummyCheck

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - id: "auth"
        if: ${{ !(inputs.PUSH  == 'false') }}
        uses: "google-github-actions/auth@v2"
        uses: "google-github-actions/auth@v2"